Repository mucahitekin/groupproject150, pull requests merged in 2021-08, with the labels that each got.

#3 Memet done project
  src/memet12/MemetWork.java
Labels: enhancement

#5 Memet did work
  src/memet555/MemetSecondWork.java
Labels: enhancement

#4 meltem's work is done
  src/group4/meltem/meltem.java
Labels: enhancement

#9 Turgay1
  src/Turgay_2nd/Turgay55.java
Labels: bug

#7 awesome codes
  src/group4/class1.java
Labels: help wanted
